apiVersion: v1
kind: Namespace
metadata:
  name: jarvis
  labels:
    name: jarvis
    version: v1.4.0
    managed-by: kubernetes
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: jarvis-quota
  namespace: jarvis
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    pods: "20"
    persistentvolumeclaims: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: jarvis-limits
  namespace: jarvis
spec:
  limits:
  - default:
      cpu: "1"
      memory: "1Gi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container