apiVersion: apps/v1
kind: Deployment
metadata:
  name: jarvis-timescale
  namespace: jarvis
  labels:
    app: jarvis-timescale
    component: timeseries-db
    version: v1.4.0
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jarvis-timescale
  template:
    metadata:
      labels:
        app: jarvis-timescale
        component: timeseries-db
    spec:
      containers:
      - name: timescale
        image: timescale/timescaledb:latest-pg15
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_DB
          value: "jarvis_timeseries"
        - name: POSTGRES_USER
          value: "jarvis"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: jarvis-secrets
              key: POSTGRES_PASSWORD
        - name: TIMESCALEDB_TELEMETRY
          value: "off"
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: timescale-storage
          mountPath: /var/lib/postgresql/data
        - name: timescale-init
          mountPath: /docker-entrypoint-initdb.d
          readOnly: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - pg_isready -U jarvis -d jarvis_timeseries
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - pg_isready -U jarvis -d jarvis_timeseries
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
      volumes:
      - name: timescale-storage
        persistentVolumeClaim:
          claimName: jarvis-timescale-pvc
      - name: timescale-init
        configMap:
          name: jarvis-timescale-init
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: jarvis-timescale
  namespace: jarvis
  labels:
    app: jarvis-timescale
    component: timeseries-db
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: jarvis-timescale