# Docker Compose pour backend audio C++ Jarvis
# S'intègre dans l'infrastructure Docker existante
# Port 8004 pour accès API

version: '3.8'

services:
  # Backend Audio C++ - Temps réel DSP <1ms latence
  jarvis-audio-engine:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jarvis_audio_engine
    ports:
      - "8004:8004"  # API HTTP
    environment:
      # Configuration runtime
      - RUST_LOG=info

    networks:
      - jarvis_network
    restart: unless-stopped

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

    # Accès aux ressources audio du host
    devices:
      - /dev/snd:/dev/snd

    # Capacités requises pour accès audio temps réel
    cap_add:
      - SYS_NICE

    # Limite de mémoire
    mem_limit: 256m
    memswap_limit: 512m

networks:
  jarvis_network:
    external: true  # Utilise le réseau existant