apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jarvis-production
  namespace: argocd
  labels:
    app: jarvis
    env: production
spec:
  project: default
  source:
    repoURL: https://github.com/enzo/Projet-Jarvis  # À adapter avec ton repo
    targetRevision: main
    path: k8s/
  destination:
    server: https://kubernetes.default.svc
    namespace: jarvis-production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jarvis-staging
  namespace: argocd
  labels:
    app: jarvis
    env: staging
spec:
  project: default
  source:
    repoURL: https://github.com/enzo/Projet-Jarvis  # À adapter avec ton repo
    targetRevision: develop
    path: k8s/
  destination:
    server: https://kubernetes.default.svc
    namespace: jarvis-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 5